from routes.registration import RegistrationAPI
from routes.user import UserAPI
from routes.auth import AuthAPI
from routes.maintenance_route import TestAPI
from routes.user_detail import UserDetailAPI
from routes.dependency import DepdenciesAPI
from routes.text_template import TextTemplateAPI
from routes.dependency_detail import DepdencyDetailAPI
from routes.income import IncomeAPI
from routes.expenses import ExpensesAPI
from routes.income_protection import IncomeProtectionAPI
from routes.lifestyle_protection import LifestyleProtectionAPI
from routes.wealth import WealthAPI