"""Update on table user

Revision ID: 04cf911f29db
Revises: f689792022ed
Create Date: 2023-05-24 00:57:56.299226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04cf911f29db'
down_revision = 'f689792022ed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('testCol', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_user_testCol'), 'user', ['testCol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_testCol'), table_name='user')
    op.drop_column('user', 'testCol')
    # ### end Alembic commands ###
