"""reapply

Revision ID: 203de01edc98
Revises: 532b3b0da80e
Create Date: 2023-05-11 03:03:38.954031

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '203de01edc98'
down_revision = '532b3b0da80e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('occupation', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.add_column('occupation', sa.Column('updated_date', sa.DateTime(), nullable=True))
    op.drop_column('occupation', 'updated_at')
    op.drop_column('occupation', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('occupation', sa.Column('created_at', mysql.DATETIME(), nullable=True))
    op.add_column('occupation', sa.Column('updated_at', mysql.DATETIME(), nullable=True))
    op.drop_column('occupation', 'updated_date')
    op.drop_column('occupation', 'created_date')
    # ### end Alembic commands ###
