"""reapply

Revision ID: a8e9bd8632db
Revises: bd000488a3dd
Create Date: 2023-05-11 01:18:50.665132

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a8e9bd8632db'
down_revision = 'bd000488a3dd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_active', table_name='user')
    op.drop_index('ix_user_date_of_birth', table_name='user')
    op.drop_index('ix_user_email_address', table_name='user')
    op.drop_index('ix_user_first_name', table_name='user')
    op.drop_index('ix_user_id', table_name='user')
    op.drop_index('ix_user_last_name', table_name='user')
    op.drop_index('ix_user_marital', table_name='user')
    op.drop_index('ix_user_middle_name', table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=35), nullable=True),
    sa.Column('last_name', mysql.VARCHAR(length=35), nullable=True),
    sa.Column('middle_name', mysql.VARCHAR(length=35), nullable=True),
    sa.Column('email_address', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('active', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_of_birth', sa.DATE(), nullable=True),
    sa.Column('marital', mysql.ENUM('single', 'married', 'divorced', 'separated', 'widowed'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_user_middle_name', 'user', ['middle_name'], unique=False)
    op.create_index('ix_user_marital', 'user', ['marital'], unique=False)
    op.create_index('ix_user_last_name', 'user', ['last_name'], unique=False)
    op.create_index('ix_user_id', 'user', ['id'], unique=False)
    op.create_index('ix_user_first_name', 'user', ['first_name'], unique=False)
    op.create_index('ix_user_email_address', 'user', ['email_address'], unique=False)
    op.create_index('ix_user_date_of_birth', 'user', ['date_of_birth'], unique=False)
    op.create_index('ix_user_active', 'user', ['active'], unique=False)
    # ### end Alembic commands ###
