"""feat

Revision ID: b2265a7bbd29
Revises: 203de01edc98
Create Date: 2023-05-11 15:48:26.176201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2265a7bbd29'
down_revision = '203de01edc98'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
