"""Update on table user

Revision ID: f689792022ed
Revises: e3afc7228c68
Create Date: 2023-05-24 00:57:06.043960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f689792022ed'
down_revision = 'e3afc7228c68'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
